# =============================================================================
# EDIT THESE VARIABLES

USERNAME=mushtu
RAINBOW_GRADES_DIRECTORY=/mnt/c/Users/mushtu/CS1010Fall2019/RainbowGrades/RainbowGrades-master
HWSERVER=submitty.cs.rpi.edu
REPORTS_DIRECTORY=/var/local/submitty/courses/f19/csci1010/reports
# =============================================================================

include ${RAINBOW_GRADES_DIRECTORY}/MakefileHelper
